### ISSUE TITLE
关于 whutmod.cls 文件的版权问题 | Copyright claim for file whutmod.cls

### ISSUE THREAD

**Issue by huangyxi** [775269512/WHUT_CUMCM20#3]
刘同学你好，我是 [武汉理工大学数学建模培训 LaTeX 模板 whutmod](https://github.com/huangyxi/whutmod) (以下简称“WHUTMOD 项目”) 的开发者 [huangyxi](https://github.com/huangyxi)。

近日有朋友告诉我阁下在项目中引用了本人的项目。
首先，本人对阁下勇于开源自己多年训练及比赛的数据和文件的行为表达感谢。
但是，阁下可能无意中在项目文件 [`whutmod.cls`](https://github.com/775269512/WHUT_CUMCM20/blob/a966c09e46c1789a86d4532f46d503a2226e0a47/%E8%AE%AD%E7%BB%83%E6%A8%A1%E6%9D%BF%EF%BC%88%E8%AF%AF%E5%8A%A8%EF%BC%89/whutmod.cls) 中**未申明来源**且**手动粘贴并修改**了 WHUTMOD 项目模板 [`whutmod.cls`](https://github.com/huangyxi/whutmod/blob/22ce39a857e15f1bd23fa329c70321626c4d6ad1/whutmod.cls) 的代码，并**未经本人许可**将包括 WHUTMOD 项目文件所在的内容 [以MIT协议开源](https://github.com/775269512/WHUT_CUMCM20/blob/a966c09e46c1789a86d4532f46d503a2226e0a47/LICENSE)。
由于 WHUTMOD 项目[尚未决定采用任何开源协议 (no license)](https://choosealicense.com/no-permission/)，即是 [专有 (proprietary) 项目](https://en.wikipedia.org/wiki/Proprietary_software)，仅仅是 [看源 (source-available)](https://en.wikipedia.org/wiki/Source-available_software) 而不是 [开源 (open-source)](https://en.wikipedia.org/wiki/Open-source_software)。根据 [GitHub 服务协议](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users):

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub … and to reproduce Your Content solely on GitHub as permitted **through GitHub's functionality (for example, through forking)**.

阁下对 WHUTMOD 项目的复制 (reproduce) 仅拥有协议许可的 fork 等 GitHub 内建功能的权利。对此，本人在此要求(满足一下所有)：
1. 删除所有对 WHUTMOD 项目的侵权代码，包括但不限于 [`whutmod.cls`](https://github.com/775269512/WHUT_CUMCM20/blob/a966c09e46c1789a86d4532f46d503a2226e0a47/%E8%AE%AD%E7%BB%83%E6%A8%A1%E6%9D%BF%EF%BC%88%E8%AF%AF%E5%8A%A8%EF%BC%89/whutmod.cls)
2. 在根目录 [`README.md`](https://github.com/775269512/WHUT_CUMCM20/blob/master/README.md) 文件中声明 WHUTMOD 项目的所有权，并附上 WHUTMOD 项目的链接 [`https://github.com/huangyxi/whutmod`](https://github.com/huangyxi/whutmod)

分享知识本无恶，上述行为相信只是阁下的无意只举。开源是一项伟大的事业，但不要以他人的权利为代价，慷他人之慨。感谢阁下的合作，祝阁下未来编程顺利！

----

Hello Mr. Liu, I am [huangyxi](https://github.com/huangyxi), the developer of project [A LaTeX Template for Mathematical Modeling Training at Wuhan University of Technology (WHUT)](https://github.com/huangyxi/whutmod) (hereinafter referred to as "WHUTMOD Project").

Recently, a friend told me that you included the WHUTMOD Project in your project.
First of all, I would like to express my gratitude to you for your dedication to open-source the data and files generated during your training and competition periods.
However, you may unintentionally **hide the source** of your project file [`whutmod.cls`](https://github.com/775269512/WHUT_CUMCM20/blob/a966c09e46c1789a86d4532f46d503a2226e0a47/%E8%AE%AD%E7%BB%83%E6%A8%A1%E6%9D%BF%EF%BC%88%E8%AF%AF%E5%8A%A8%EF%BC%89/whutmod.cls), **manually paste and modify** the codes from WHUTMOD project file `whutmod.cls`, and [make these contents open-sourced under the MIT license](https://github.com/775269512/WHUT_CUMCM20/blob/a966c09e46c1789a86d4532f46d503a2226e0a47/LICENSE) **without my authorization**.
Since the WHUTMOD project has not yet decided to adopt any open-source license ([no license](https://choosealicense.com/no-permission/)), it is a [proprietary project](https://en.wikipedia.org/wiki/Proprietary_software), just [source-available](https://en.wikipedia.org/wiki/Source-available_software) instead of [open-source](https://en.wikipedia.org/wiki/Open-source_software). According to [GitHub Terms of Service](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users):

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub … and to reproduce Your Content solely on GitHub as permitted **through GitHub's functionality (for example, through forking)**.

your reproduction of the WHUTMOD project is limited to fork and other GitHub's functionality under the terms. In this regard, I hereby request (apply all):
1. Delete all infringing codes from WHUTMOD project, including but not limited to [`whutmod.cls`](https://github.com/775269512/WHUT_CUMCM20/blob/a966c09e46c1789a86d4532f46d503a2226e0a47/%E8%AE%AD%E7%BB%83%E6%A8%A1%E6%9D%BF%EF%BC%88%E8%AF%AF%E5%8A%A8%EF%BC%89/whutmod.cls)
2. Declare the ownership of WHUTMOD project in file [`README.md`](https://github.com/775269512/WHUT_CUMCM20/blob/master/README.md), and attach the link of WHUTMOD project [`https://github.com/huangyxi/whutmod`](https://github.com/huangyxi/whutmod)

There is no evil in sharing knowledge, and the above behavior is believed to be your unintentional act. Open-source is a great cause, but don't be generous at others' rights. Thanks for your cooperation. Happy coding!

**Comment by 775269512** [comment]
您好，不好意思之前没有看到您的issue。之前只是把文件放在github上，也没在意会有这么多关注。目前您所提到的whutmod.cls此项目都有删除，并且引用了您的仓库。您看现在可以吗

**Comment by zichuan-liu** [comment]
您好，不好意思之前没有看到您的issue。之前只是把数模的文件整理放在github上，也没在意会有这么多关注。目前您所提到的whutmod.cls此项目都有删除，并且引用了您的仓库。您看现在可以吗

**Comment by huangyxi** [comment]
首先肯定阁下在近半年之后终于有勇气正视自己项目中的著作权侵权问题。

由于git历史记录仍然残留侵权文件，理应清空仓库并强制推送或将仓库设为私有。
但从[数次`README.md`变更](https://github.com/775269512/WHUT_CUMCM20/commits/master/README.md)中考虑到阁下[对star和fork数字的执着](https://github.com/775269512/WHUT_CUMCM20/blob/effc5f96e78d8b7086234010e853e62360b5c4bf/README.md?plain=1#L5)，对清空仓库、设为私有等操作不做强求，但是，
需要将贵项目的主分支（当前为master）最新版以pull request形式推送到自 de32d3948b0998449fe2a1a9ef88c702b5a500f2 （首次引入`whutmod.cls`文件）至 d77ed69edeb1b1f082212f626e73c2aff96af3ef （移除`whutmod.cls`文件）期间fork贵项目的[所有分支项目](https://github.com/775269512/WHUT_CUMCM20/network/members)的主分支（默认为master或main，依实际情况而定）中，并在pull request标题及正文中说明原因。

**Comment by zichuan-liu** [comment]
您好，已经按照您的要求，PR了所有分支仓库到目前最新版的项目分支，e.g. [PR示例](https://github.com/albbbert6/WHUT_CUMCM20/pull/1)，我对涉嫌侵权的问题再次深表歉意，并深刻意识到版权问题，还请您海涵！并且很抱歉因为个人原因未及时查看issues，是在您提醒下才看到导致回复较晚。此项目也仅是数模过程中的记录与文件整理，并没涉及其他利用价值，希望您能理解。最后对侵权问题深表歉意，祝学长前程似锦。

**Comment by huangyxi** [comment]
人非圣贤，孰能无过？过而能改，善莫大焉。祝好。
